[tool.poetry]
authors = ["OlegSmoliakov <smailzpro@gmail.com>"]
name = "pysikuli"
version = "0.0.8"
description = "Fast cross-platform RPA tool for GUI automation"
readme = "README.md"
license = "LICENSE.txt"
keywords = ["gui", "automation", "desktop", "RPA", "testing"]
classifiers = [
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent",
    "Topic :: Home Automation",
    "Topic :: Software Development :: Testing",
    "Development Status :: 3 - Alpha",
    "Topic :: Utilities",
]


[tool.poetry.dependencies]
python = "^3.10"
wheel = "^0.41.3"
pyautogui = "^0.9.54"
opencv-python = "^4.8.1.78"
mss = "^9.0.1"
send2trash = "^1.8.2"
pyhotkey = "^1.5.0"
numpy = "^1.26.2"
# playsound = {git = "https://github.com/killjoy1221/playsound.git"}
pygobject = "^3.46.0"



[tool.poetry.group.dev.dependencies]
pyinstrument = "^4.6.1"
twine = "^4.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
