[build-system]
requires = [
    "setuptools >= 68.2",
    "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "pysikuli"
version = "0.0.1"
authors = [
  { name="Oleg Smoliakov"},
]
description = "Fast cross-platform python module for gui automation"
readme = "README.md"
requires-python = ">=3.11"
license = {file = "LICENSE"}
keywords = ["gui", "automation", "desktop", "opencv"]
classifiers = [
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Programming Language :: Python :: 3.11",
    "Operating System :: OS Independent",
    "Topic :: Home Automation",
    "Topic :: Software Development :: Testing",
    "Development Status :: 3 - Alpha",
    "Topic :: Utilities",
]

dependencies = [
    "opencv-python >= 4.8.1.78",
    "pyautogui >= 0.9.54",
    "mss >= 9.0.1",
    "send2trash >= 1.8.2",
    "pyhotkey >= 1.5.0",
    "playsound >= 1.3.0"
]

[project.optional-dependencies]
dev = ["pytest", "pyinstrument", "twine"]

[project.urls]
"Repository" = "https://github.com/OlegSmoliakov/pysikui"
"Bug Tracker" = "https://github.com/OlegSmoliakov/pysikui/issues"