version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  apt_packages:
    - xvfb
  jobs:
    pre_create_environment:
      - Xvfb :0 & export DISPLAY=:0
      - export XDG_SESSION_TYPE=x11

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true

formats:
  - pdf
  - epub