version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"

python:
  install:
    - requirements: docs/requirements.txt
  jobs:
    pre_build:
      - apt install xvfb
      - Xvfb :99 & export DISPLAY=:99

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true

formats:
  - pdf
  - epub