version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  apt_packages:
    - xvfb
  jobs:
    pre_build:
      - Xvfb :99
      - export DISPLAY=:99

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true

formats:
  - pdf
  - epub